version: '3'

services:
  web:
    build: ./web/
    ports:
      - 8899:80
    volumes:
      - .:/var/www/html
    depends_on:
      - db
  db:
    image: postgres:11-alpine
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - 5433:5432
    volumes:
      - ./db:/docker-entrypoint-initdb.d
